# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/MyData/vivado/01rgb2gray/01rgb2gray.srcs/sources_1/ip/shift_RAM_3X3_8bit/shift_RAM_3X3_8bit.xci
# IP: The module: 'shift_RAM_3X3_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MyData/vivado/01rgb2gray/01rgb2gray.srcs/sources_1/ip/shift_RAM_3X3_8bit/shift_RAM_3X3_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_RAM_3X3_8bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/MyData/vivado/01rgb2gray/01rgb2gray.srcs/sources_1/ip/shift_RAM_3X3_8bit/shift_RAM_3X3_8bit.xci
# IP: The module: 'shift_RAM_3X3_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MyData/vivado/01rgb2gray/01rgb2gray.srcs/sources_1/ip/shift_RAM_3X3_8bit/shift_RAM_3X3_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_RAM_3X3_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
